name: gdbh

on:
  workflow_dispatch:
  schedule:
     - cron: '3 2 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行【gdbh】'     
        run: |
          node Task/gdbh.js
        env:
          gdbhhd: ${{ secrets.gdbhhd }}
          gdbhurl: ${{ secrets.gdbhurl }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
